export const Styles = {
  container: {
    minHeight: "100vh",
    background: "#f8f9fa",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
  },
  header: {
    background: "#ffffff",
    borderBottom: "1px solid #e9ecef",
    padding: "20px 24px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.05)",
  },
  headerContent: {
    maxWidth: "1400px",
    margin: "0 auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: "20px",
  },
  headerTitle: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
  },
  iconBox: {
    background: "#0d6efd",
    padding: "12px",
    borderRadius: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  balanceCards: {
    display: "flex",
    gap: "16px",
  },
  balanceCard: {
    background: "#f8f9fa",
    border: "1px solid #e9ecef",
    borderRadius: "8px",
    padding: "16px 20px",
    minWidth: "140px",
  },
  balanceLabel: {
    fontSize: 13,
    color: "#6c757d",
    marginBottom: "4px",
    fontWeight: "500",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  balanceAmount: {
    fontSize: 24,
    fontWeight: "700",
    color: "#212529",
  },

  tabs: {
    background: "white",
    borderBottom: "1px solid #e9ecef",
  },
  tabsContainer: {
    maxWidth: "1400px",
    margin: "0 auto",
    display: "flex",
    gap: "0",
    padding: "0 24px",
  },
  tab: {
    padding: "16px 28px",
    border: "none",
    background: "transparent",
    cursor: "pointer",
    fontWeight: "500",
    fontSize: 15,
    color: "#6c757d",
    borderBottom: "3px solid transparent",
    transition: "all 0.2s",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  tabActive: {
    color: "#0d6efd",
    borderBottom: "3px solid #0d6efd",
    background: "transparent",
  },

  content: {
    maxWidth: "1400px",
    margin: "0 auto",
    padding: "32px 24px",
  },

  paper: {
    background: "white",
    borderRadius: "8px",
    padding: "32px",
    border: "1px solid #e9ecef",
    boxShadow: "0 1px 2px rgba(0,0,0,0.05)",
  },

  formGroup: {
    marginBottom: "24px",
  },
  label: {
    display: "block",
    marginBottom: "8px",
    fontWeight: "600",
    fontSize: 14,
    color: "#212529",
  },
  input: {
    width: "100%",
    padding: "12px 16px",
    border: "1px solid #dee2e6",
    borderRadius: "6px",
    fontSize: 15,
    transition: "all 0.2s",
    outline: "none",
    backgroundColor: "#fff",
  },
  button: {
    width: "100%",
    padding: "14px 24px",
    border: "none",
    borderRadius: "6px",
    fontSize: 15,
    fontWeight: "600",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    transition: "all 0.2s",
    color: "white",
  },
  buttonPrimary: {
    background: "#0d6efd",
    boxShadow: "0 1px 2px rgba(0,0,0,0.05)",
  },
  buttonSuccess: {
    background: "#198754",
    boxShadow: "0 1px 2px rgba(0,0,0,0.05)",
  },
  textarea: {
    width: "100%",
    padding: "12px 16px",
    border: "1px solid #dee2e6",
    borderRadius: "6px",
    fontSize: 14,
    fontFamily:
      '"SF Mono", Monaco, "Cascadia Code", "Roboto Mono", Consolas, "Courier New", monospace',
    resize: "vertical",
    outline: "none",
    backgroundColor: "#fff",
    lineHeight: "1.6",
  },
  alert: {
    padding: "16px 20px",
    borderRadius: "6px",
    marginBottom: "24px",
    display: "flex",
    alignItems: "center",
    gap: "12px",
    background: "#d1e7dd",
    border: "1px solid #badbcc",
    color: "#0f5132",
    fontWeight: "500",
  },
  infoBox: {
    background: "#e7f1ff",
    border: "1px solid #b6d4fe",
    borderRadius: "6px",
    padding: "16px 20px",
    marginBottom: "24px",
  },
  table: {
    width: "100%",
    borderCollapse: "separate",
    borderSpacing: "0",
  },
  th: {
    background: "#f8f9fa",
    padding: "14px 16px",
    textAlign: "left",
    fontWeight: "600",
    fontSize: 13,
    color: "#495057",
    borderBottom: "2px solid #dee2e6",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  td: {
    padding: "16px",
    borderBottom: "1px solid #e9ecef",
    fontSize: 15,
    color: "#212529",
  },
  chip: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "6px 14px",
    borderRadius: "20px",
    fontSize: 13,
    fontWeight: "600",
  },
  chipSuccess: {
    background: "#d1e7dd",
    color: "#0f5132",
  },
  chipError: {
    background: "#f8d7da",
    color: "#842029",
  },
  searchContainer: {
    position: "relative",
    flex: 1,
  },
  searchIcon: {
    position: "absolute",
    left: "14px",
    top: "50%",
    transform: "translateY(-50%)",
    color: "#6c757d",
  },
};

export default Styles;
